name: time
description: Type-safe DateTime and Duration calculations, powered by extensions.
version: 2.1.5
homepage: https://github.com/jogboms/time.dart

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  clock: ">=1.1.1 <2.0.0"

funding:
  - https://www.paypal.me/jogboms
  - https://www.buymeacoffee.com/jogboms

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  coverage: ^1.11.0
