name: time
description: Type-safe DateTime and Duration calculations, powered by extensions.
version: 2.1.2
homepage: https://github.com/jogboms/time.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clock: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
  test_coverage:
    git:
      url: https://github.com/timsneath/test-coverage.git
