name: time
description: Type-safe time calculations, powered by extensions.
version: 0.0.1+1
homepage: https://github.com/jogboms/time.dart
author: Jogboms <jeremiahogbomo@gmail.com>

environment:
  sdk: '>=2.6.0-dev <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.0
  test_coverage:
    git:
      url: https://github.com/jogboms/test-coverage.git
